print("Baseball Teams")
players = int(input("Enter number of players: "))
teams = int((players/ 9))
leftovers = int(9 % teams)
print ("There can be " + str(teams) + " teams with " + str(leftovers) + " extra players.")

firstName = input("Enter your first name: ")
lastName = input("Enter your last name: ")
momName = input("Enter Mother's maiden name: ")
cityName = input("Enter birth town: ")
firstThree = (firstName[0:3])
lastTwo = (lastName[0:2])
mother = (momName[0:2])
city = (cityName[0:3])
print ("Your Star Wars name is " + firstThree[0].upper() + firstThree[1:3].lower() + lastTwo.lower() + " " + mother[0].upper() + mother[1:3].lower() + city.lower())